# ndarray

In [2]:
import numpy as np
a = np.arange(10)
s = slice(2,7,2)
a[s]

array([2, 4, 6])

***

In [2]:
import numpy as np
a = np.arange(10)
s = a[2:7:2]
s

array([2, 4, 6])

***

In [3]:
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
list(range(10))[2:]

[2, 3, 4, 5, 6, 7, 8, 9]