In [1]:
import numpy as p 
p.ndarray([1,2,3])

TypeError: shape() missing 1 required positional argument: 'a'

### 一维

In [5]:
p.array([1,2,3])

array([1, 2, 3])

### 二维

In [6]:
p.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

### 最小维度

In [8]:
p.array([1,2,3,4,5],ndmin=3)

array([[[1, 2, 3, 4, 5]]])

### dtype

In [9]:
p.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])