# 二维数组切片

In [3]:
import numpy as np
a = np.array([ [1,2,3],[3,4,5],[5,6,7] ])

print(a[1:])

[[3 4 5]
 [5 6 7]]


In [5]:
a[...,1]

array([2, 4, 6])

In [6]:
a[1,...]

array([3, 4, 5])

In [7]:
a[...,1:]

array([[2, 3],
       [4, 5],
       [6, 7]])